apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pingExporter.fullname" . }}
data:
  config.yml: |
    targets:
      {{- toYaml .Values.config.targets | nindent 6 }}
    dns:
      {{- toYaml .Values.config.dns | nindent 6 }}
    ping:
      {{- toYaml .Values.config.ping | nindent 6 }}
