{{- if .Values.secrets.sentryApiKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sentry.fullname" . }}
  labels:
    {{- include "sentry.labels" . | nindent 4 }}
type: Opaque
data:
  sentryApiKey: {{ .Values.secrets.sentryApiKey | b64enc }}
{{- end -}}
