apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "postgres-backup.fullname" . }}
  labels:
    {{- include "postgres-backup.labels" . | nindent 4 }}
spec:
  suspend: {{ .Values.cronjob.suspend }}
  schedule: {{ .Values.cronjob.schedule | quote }}
  startingDeadlineSeconds: {{ .Values.cronjob.startingDeadlineSeconds }}
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.cronjob.job.backoffLimit }}
      template:
        metadata:
          labels:
            {{- include "postgres-backup.labels" . | nindent 12 }}
        spec:
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                - name: NODE_ENV
                  value: production
              {{- with .Values.cronjob.container.envFrom }}
              envFrom:
                {{- toYaml . | nindent 16 }}
              {{- end }}
          restartPolicy: {{ .Values.cronjob.container.restartPolicy }}
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
