apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    {{- include "wandb.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "wandb.selectorLabels" . | nindent 6 }}
      app: mysql
  template:
    metadata:
      labels:
        {{- include "wandb.selectorLabels" . | nindent 8 }}
        app: mysql
    spec:
      {{- with .Values.mysql.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "wandb.serviceAccountName" . }}
      containers:
        - name: mysql
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
          args: ["--ignore-db-dir=lost+found"]
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          resources:
            {{- toYaml .Values.mysql.resources | nindent 12 }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: MYSQL_ROOT_PASSWORD
                  optional: false 
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: MYSQL_USER
                  optional: false 
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: MYSQL_PASSWORD
                  optional: false 
            - name: MYSQL_DATABASE
              value: "wandb"
          volumeMounts:
          - mountPath: "/var/lib/mysql"
            name: mysql
      volumes:
        - name: mysql
          persistentVolumeClaim:
            claimName: mysql
