{{- if .Values.minio.ingress.enabled -}}
{{- $svcPort := .Values.minio.service.consolePort -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: minio
spec:
  rules:
    - host: {{ .Values.minio.ingress.host | quote }}
      http:
        paths:
          {{- range .Values.minio.ingress.paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: minio
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: minio
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
{{- end }}
