apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    {{- include "wandb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mysql.service.type }}
  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: {{ .Values.mysql.service.targetPort }}
      protocol: TCP
      name: mysql
  selector:
    {{- include "wandb.selectorLabels" . | nindent 4 }}
    app: mysql
