apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "common.names.fullname" . }}
  labels:
    {{- include "rmqmto.labels" . | nindent 4 }}
spec:
  dnsNames:
    - {{ template "common.names.fullname" . }}.{{ .Release.Namespace }}.svc
    - {{ template "common.names.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ template "common.names.fullname" . }}
  secretName: {{ template "common.names.fullname" . }}
