apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.names.fullname" . }}
  labels:
    {{- include "rmqmto.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    {{- include "rmqmto.selectorLabels" . | nindent 4 }}
