global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: ""

nameOverride: ""
fullnameOverride: ""

image:
  registry: docker.io
  repository: rabbitmqoperator/messaging-topology-operator
  tag: "1.2.1"
  pullPolicy: Always
  pullSecrets: []

livenessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 30
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 30
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5

startupProbe:
  enabled: false
  initialDelaySeconds: 5
  periodSeconds: 30
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5

customLivenessProbe: {}
customReadinessProbe: {}
customStartupProbe: {}

resources:
  limits:
    cpu: 300m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 100Mi

# extraEnvVars:
#   - name: FOO
#     value: "bar"
#
extraEnvVars: []
extraEnvVarsCM: ""
extraEnvVarsSecret: ""
